// Sample AR Books data

import { ARBook, ARBookCategory } from './types';

export const arBookCategories: ARBookCategory[] = [
    {
        id: 'alphabet',
        name: 'Alphabets & Phonics',
        icon: '📚',
        description: 'Learn English alphabets with interactive AR models',
        bookCount: 5,
    },
    {
        id: 'numbers',
        name: 'Numbers & Counting',
        icon: '🔢',
        description: 'Interactive number learning with 3D models',
        bookCount: 4,
    },
    {
        id: 'animals',
        name: 'Animals & Nature',
        icon: '🦁',
        description: 'Discover animals with immersive AR experience',
        bookCount: 6,
    },
    {
        id: 'shapes',
        name: 'Shapes & Colors',
        icon: '🌈',
        description: 'Learn shapes and colors interactively',
        bookCount: 4,
    },
    {
        id: 'stories',
        name: 'Stories & Tales',
        icon: '📖',
        description: 'Animated stories with augmented reality',
        bookCount: 5,
    },
    {
        id: 'science',
        name: 'Science & Discovery',
        icon: '🔬',
        description: 'Explore scientific concepts in 3D',
        bookCount: 3,
    },
];

export const arBooks: ARBook[] = [
    {
        id: 'book-001',
        title: 'ABC Adventure: Learn Alphabets',
        description: 'An interactive journey through the English alphabet with 3D AR models and pronunciation guides.',
        coverImage: '/assets/ar-books/alphabet-cover.jpg',
        category: 'alphabet',
        ageGroup: '2-4 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-01-15',
        isFeatured: true,
        views: 1250,
        rating: 4.8,
        pages: [
            {
                id: 'page-001',
                pageNumber: 1,
                title: 'A is for Apple',
                description: 'Learn the letter A with a beautiful 3D apple model',
                imageUrl: '/assets/ar-books/alphabet/page-1.jpg',
                arModelUrl: '/models/apple.glb',
                audioUrl: '/audio/apple-pronunciation.mp3',
                interactiveElements: [
                    {
                        id: 'apple-hotspot',
                        type: 'hotspot',
                        name: 'Tap to Animate Apple',
                        action: 'play_animation',
                    },
                ],
            },
            {
                id: 'page-002',
                pageNumber: 2,
                title: 'B is for Ball',
                description: 'Learn the letter B with an interactive ball',
                imageUrl: '/assets/ar-books/alphabet/page-2.jpg',
                arModelUrl: '/models/ball.glb',
                audioUrl: '/audio/ball-pronunciation.mp3',
                interactiveElements: [
                    {
                        id: 'ball-hotspot',
                        type: 'hotspot',
                        name: 'Tap to Roll Ball',
                        action: 'play_animation',
                    },
                ],
            },
        ],
    },
    {
        id: 'book-002',
        title: '123 Count & Learn',
        description: 'Learn numbers 1-10 with engaging 3D models and counting activities.',
        coverImage: '/assets/ar-books/numbers-cover.jpg',
        category: 'numbers',
        ageGroup: '2-4 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-01-20',
        isFeatured: true,
        views: 980,
        rating: 4.7,
        pages: [
            {
                id: 'page-101',
                pageNumber: 1,
                title: 'Number 1 - One Apple',
                description: 'Learn number 1 with one apple',
                imageUrl: '/assets/ar-books/numbers/page-1.jpg',
                arModelUrl: '/models/apple.glb',
                audioUrl: '/audio/number-1.mp3',
            },
        ],
    },
    {
        id: 'book-003',
        title: 'Wild Animals Expedition',
        description: 'Explore wild animals in their natural habitats with amazing 3D AR models.',
        coverImage: '/assets/ar-books/animals-cover.jpg',
        category: 'animals',
        ageGroup: '3-5 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-02-01',
        isFeatured: true,
        views: 1500,
        rating: 4.9,
        pages: [
            {
                id: 'page-201',
                pageNumber: 1,
                title: 'The Mighty Lion',
                description: 'Meet the king of the jungle',
                imageUrl: '/assets/ar-books/animals/lion-page.jpg',
                arModelUrl: '/models/lion.glb',
                audioUrl: '/audio/lion-roar.mp3',
                interactiveElements: [
                    {
                        id: 'lion-sound',
                        type: 'button',
                        name: 'Listen to Roar',
                        action: 'play_sound',
                    },
                ],
            },
        ],
    },
    {
        id: 'book-004',
        title: 'Rainbow Shapes',
        description: 'Learn geometric shapes in vibrant colors with interactive 3D models.',
        coverImage: '/assets/ar-books/shapes-cover.jpg',
        category: 'shapes',
        ageGroup: '2-4 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-02-10',
        isFeatured: false,
        views: 750,
        rating: 4.6,
        pages: [],
    },
    {
        id: 'book-005',
        title: 'Magical Tales',
        description: 'Enchanting stories brought to life with augmented reality animations.',
        coverImage: '/assets/ar-books/stories-cover.jpg',
        category: 'stories',
        ageGroup: '3-5 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-02-15',
        isFeatured: false,
        views: 1100,
        rating: 4.8,
        pages: [],
    },
    {
        id: 'book-006',
        title: 'Science Explorer',
        description: 'Discover the wonders of science with interactive 3D experiments.',
        coverImage: '/assets/ar-books/science-cover.jpg',
        category: 'science',
        ageGroup: '4-6 years',
        authorName: 'Ditvi Team',
        publishedDate: '2024-02-20',
        isFeatured: true,
        views: 890,
        rating: 4.7,
        pages: [],
    },
];

export const defaultARBook: ARBook = {
    id: 'book-default',
    title: 'Welcome to AR Books',
    description: 'Start your journey with augmented reality learning',
    coverImage: '/assets/ar-books/default-cover.jpg',
    category: 'alphabet',
    ageGroup: '2-6 years',
    authorName: 'Ditvi Team',
    publishedDate: '2024-01-01',
    isFeatured: false,
    views: 0,
    rating: 5,
    pages: [],
};
