// Sample AR Books data

import { ARBook, ARBookCategory } from './types';

export const arBookCategories: ARBookCategory[] = [
    {
        id: 'alphabet',
        name: 'Alphabets & Phonics',
        icon: 'BOOKS',
        description: 'Learn English alphabets with interactive AR models',
        bookCount: 5,
    },
    {
        id: 'numbers',
        name: 'Numbers & Counting',
        icon: 'NUMBERS',
        description: 'Interactive number learning with 3D models',
        bookCount: 4,
    },
    {
        id: 'animals',
        name: 'Animals & Nature',
        icon: 'ANIMALS',
        description: 'Discover animals with immersive AR experience',
        bookCount: 6,
    },
    {
        id: 'shapes',
        name: 'Shapes & Colors',
        icon: 'SHAPES',
        description: 'Learn shapes and colors interactively',
        bookCount: 4,
    },
    {
        id: 'stories',
        name: 'Stories & Tales',
        icon: 'STORIES',
        description: 'Animated stories with augmented reality',
        bookCount: 5,
    },
    {
        id: 'science',
        name: 'Science & Discovery',
        icon: 'SCIENCE',
        description: 'Explore scientific concepts in 3D',
        bookCount: 3,
    },
];

export const arBooks: ARBook[] = [
    {
        id: 'book-001',
        title: 'ABC Adventure: Learn Alphabets',
        description: 'An interactive journey through the English alphabet with 3D AR models and pronunciation guides.',
        coverImage: '/assets/ar-books/alphabet-cover.jpg',
        category: 'alphabet',
        ageGroup: '2-4 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-01-15',
        isFeatured: true,
        views: 1250,
        rating: 4.8,
        pages: [
            {
                id: 'page-001',
                pageNumber: 1,
                title: 'A is for Apple',
                description: 'Learn the letter A with a 3D apple model',
                imageUrl: '/assets/scanimage/pattern-apple.png',
                arModelUrl: '/models/apple.glb',
                audioUrl: '/audio/apple-pronunciation.mp3',
                interactiveElements: [
                    { id: 'apple-hotspot', type: 'hotspot', name: 'Tap to Animate Apple', action: 'play_animation' },
                ],
            },
            {
                id: 'page-002',
                pageNumber: 2,
                title: 'B is for Butterfly',
                description: 'Learn the letter B with a colorful butterfly',
                imageUrl: '/assets/scanimage/pattern-butterfly.png',
                arModelUrl: '/models/butterfly.glb',
                audioUrl: '/audio/butterfly-pronunciation.mp3',
                interactiveElements: [
                    { id: 'butterfly-hotspot', type: 'hotspot', name: 'Tap to Flutter Wings', action: 'play_animation' },
                ],
            },
            {
                id: 'page-003',
                pageNumber: 3,
                title: 'C is for Cat',
                description: 'Learn the letter C with a playful cat model',
                imageUrl: '/assets/scanimage/pattern-cat.png',
                arModelUrl: '/models/cat.glb',
                audioUrl: '/audio/cat-pronunciation.mp3',
                interactiveElements: [
                    { id: 'cat-hotspot', type: 'hotspot', name: 'Tap to Meow', action: 'play_animation' },
                ],
            },
            {
                id: 'page-004',
                pageNumber: 4,
                title: 'D is for Dog',
                description: 'Learn the letter D with a friendly dog model',
                imageUrl: '/assets/scanimage/pattern-dog.png',
                arModelUrl: '/models/dog.glb',
                audioUrl: '/audio/dog-pronunciation.mp3',
                interactiveElements: [
                    { id: 'dog-hotspot', type: 'hotspot', name: 'Tap to Bark', action: 'play_animation' },
                ],
            },
            {
                id: 'page-005',
                pageNumber: 5,
                title: 'E is for Elephant',
                description: 'Learn the letter E with a gentle elephant model',
                imageUrl: '/assets/scanimage/pattern-elephant.png',
                arModelUrl: '/models/elephant.glb',
                audioUrl: '/audio/elephant-pronunciation.mp3',
                interactiveElements: [
                    { id: 'elephant-hotspot', type: 'hotspot', name: 'Tap to Trumpet', action: 'play_animation' },
                ],
            },
            {
                id: 'page-006',
                pageNumber: 6,
                title: 'F is for Football',
                description: 'Learn the letter F with an interactive football',
                imageUrl: '/assets/scanimage/pattern-football.png',
                arModelUrl: '/models/football.glb',
                audioUrl: '/audio/football-pronunciation.mp3',
                interactiveElements: [
                    { id: 'football-hotspot', type: 'hotspot', name: 'Tap to Kick', action: 'play_animation' },
                ],
            },
            {
                id: 'page-007',
                pageNumber: 7,
                title: 'G is for Guitar',
                description: 'Learn the letter G with a musical guitar model',
                imageUrl: '/assets/scanimage/pattern-guitar.png',
                arModelUrl: '/models/guitar.glb',
                audioUrl: '/audio/guitar-pronunciation.mp3',
                interactiveElements: [
                    { id: 'guitar-hotspot', type: 'hotspot', name: 'Tap to Play Guitar', action: 'play_animation' },
                ],
            },
            {
                id: 'page-008',
                pageNumber: 8,
                title: 'H is for Horse',
                description: 'Learn the letter H with a horse model',
                imageUrl: '/assets/scanimage/pattern-horse.png',
                arModelUrl: '/models/horse.glb',
                audioUrl: '/audio/horse-pronunciation.mp3',
                interactiveElements: [
                    { id: 'horse-hotspot', type: 'hotspot', name: 'Tap to Gallop', action: 'play_animation' },
                ],
            },
            {
                id: 'page-009',
                pageNumber: 9,
                title: 'I is for Ice Cream',
                description: 'Learn the letter I with a tasty ice cream model',
                imageUrl: '/assets/scanimage/pattern-ice-cream.png',
                arModelUrl: '/models/icecream.glb',
                audioUrl: '/audio/icecream-pronunciation.mp3',
                interactiveElements: [
                    { id: 'icecream-hotspot', type: 'hotspot', name: 'Tap to Melt', action: 'play_animation' },
                ],
            },
            {
                id: 'page-010',
                pageNumber: 10,
                title: 'J is for Jeep',
                description: 'Learn the letter J with a jeep model',
                imageUrl: '/assets/scanimage/pattern-jeep.png',
                arModelUrl: '/models/jeep.glb',
                audioUrl: '/audio/jeep-pronunciation.mp3',
                interactiveElements: [
                    { id: 'jeep-hotspot', type: 'hotspot', name: 'Tap to Honk', action: 'play_animation' },
                ],
            },
            {
                id: 'page-011',
                pageNumber: 11,
                title: 'K is for Kettle',
                description: 'Learn the letter K with a kettle model',
                imageUrl: '/assets/scanimage/pattern-kettle.png',
                arModelUrl: '/models/kettle.glb',
                audioUrl: '/audio/kettle-pronunciation.mp3',
                interactiveElements: [
                    { id: 'kettle-hotspot', type: 'hotspot', name: 'Tap to Boil', action: 'play_animation' },
                ],
            },
            {
                id: 'page-012',
                pageNumber: 12,
                title: 'L is for Lion',
                description: 'Learn the letter L with a roaring lion model',
                imageUrl: '/assets/scanimage/pattern-lion.png',
                arModelUrl: '/models/lion.glb',
                audioUrl: '/audio/lion-pronunciation.mp3',
                interactiveElements: [
                    { id: 'lion-hotspot', type: 'hotspot', name: 'Tap to Roar', action: 'play_animation' },
                ],
            },
            {
                id: 'page-013',
                pageNumber: 13,
                title: 'M is for Mango',
                description: 'Learn the letter M with a juicy mango model',
                imageUrl: '/assets/scanimage/pattern-mango.png',
                arModelUrl: '/models/mango.glb',
                audioUrl: '/audio/mango-pronunciation.mp3',
                interactiveElements: [
                    { id: 'mango-hotspot', type: 'hotspot', name: 'Tap to Slice', action: 'play_animation' },
                ],
            },
            {
                id: 'page-014',
                pageNumber: 14,
                title: 'N is for Nest',
                description: 'Learn the letter N with a bird nest model',
                imageUrl: '/assets/scanimage/pattern-nest.png',
                arModelUrl: '/models/nest.glb',
                audioUrl: '/audio/nest-pronunciation.mp3',
                interactiveElements: [
                    { id: 'nest-hotspot', type: 'hotspot', name: 'Tap to Hatch Eggs', action: 'play_animation' },
                ],
            },
            {
                id: 'page-015',
                pageNumber: 15,
                title: 'O is for Orange',
                description: 'Learn the letter O with a fresh orange model',
                imageUrl: '/assets/scanimage/pattern-orange.png',
                arModelUrl: '/models/orange.glb',
                audioUrl: '/audio/orange-pronunciation.mp3',
                interactiveElements: [
                    { id: 'orange-hotspot', type: 'hotspot', name: 'Tap to Peel', action: 'play_animation' },
                ],
            },
            {
                id: 'page-016',
                pageNumber: 16,
                title: 'P is for Penguin',
                description: 'Learn the letter P with a penguin model',
                imageUrl: '/assets/scanimage/pattern-peng.png',
                arModelUrl: '/models/penguin.glb',
                audioUrl: '/audio/penguin-pronunciation.mp3',
                interactiveElements: [
                    { id: 'penguin-hotspot', type: 'hotspot', name: 'Tap to Waddle', action: 'play_animation' },
                ],
            },
            {
                id: 'page-017',
                pageNumber: 17,
                title: 'Q is for Quack',
                description: 'Learn the letter Q with a quack/duck-themed model',
                imageUrl: '/assets/scanimage/pattern-quack.png',
                arModelUrl: '/models/quack.glb',
                audioUrl: '/audio/quack-pronunciation.mp3',
                interactiveElements: [
                    { id: 'quack-hotspot', type: 'hotspot', name: 'Tap to Quack', action: 'play_animation' },
                ],
            },
            {
                id: 'page-018',
                pageNumber: 18,
                title: 'R is for Rose',
                description: 'Learn the letter R with a blooming rose model',
                imageUrl: '/assets/scanimage/pattern-rose.png',
                arModelUrl: '/models/rose.glb',
                audioUrl: '/audio/rose-pronunciation.mp3',
                interactiveElements: [
                    { id: 'rose-hotspot', type: 'hotspot', name: 'Tap to Bloom', action: 'play_animation' },
                ],
            },
            {
                id: 'page-019',
                pageNumber: 19,
                title: 'S is for Snowman',
                description: 'Learn the letter S with a snowman model',
                imageUrl: '/assets/scanimage/pattern-snowman.png',
                arModelUrl: '/models/snowman.glb',
                audioUrl: '/audio/snowman-pronunciation.mp3',
                interactiveElements: [
                    { id: 'snowman-hotspot', type: 'hotspot', name: 'Tap to Melt', action: 'play_animation' },
                ],
            },
            {
                id: 'page-020',
                pageNumber: 20,
                title: 'T is for Tiger',
                description: 'Learn the letter T with a striped tiger model',
                imageUrl: '/assets/scanimage/pattern-tiger.png',
                arModelUrl: '/models/tiger.glb',
                audioUrl: '/audio/tiger-pronunciation.mp3',
                interactiveElements: [
                    { id: 'tiger-hotspot', type: 'hotspot', name: 'Tap to Growl', action: 'play_animation' },
                ],
            },
            {
                id: 'page-021',
                pageNumber: 21,
                title: 'U is for Umbrella',
                description: 'Learn the letter U with a colorful umbrella model',
                imageUrl: '/assets/scanimage/pattern-umbrella.png',
                arModelUrl: '/models/umbrella.glb',
                audioUrl: '/audio/umbrella-pronunciation.mp3',
                interactiveElements: [
                    { id: 'umbrella-hotspot', type: 'hotspot', name: 'Tap to Open', action: 'play_animation' },
                ],
            },
            {
                id: 'page-022',
                pageNumber: 22,
                title: 'V is for Violin',
                description: 'Learn the letter V with a musical violin model',
                imageUrl: '/assets/scanimage/pattern-violin.png',
                arModelUrl: '/models/violin.glb',
                audioUrl: '/audio/violin-pronunciation.mp3',
                interactiveElements: [
                    { id: 'violin-hotspot', type: 'hotspot', name: 'Tap to Play', action: 'play_animation' },
                ],
            },
            {
                id: 'page-023',
                pageNumber: 23,
                title: 'W is for Watermelon',
                description: 'Learn the letter W with a fresh watermelon model',
                imageUrl: '/assets/scanimage/pattern-watermelon.png',
                arModelUrl: '/models/watermelon.glb',
                audioUrl: '/audio/watermelon-pronunciation.mp3',
                interactiveElements: [
                    { id: 'watermelon-hotspot', type: 'hotspot', name: 'Tap to Slice', action: 'play_animation' },
                ],
            },
            {
                id: 'page-024',
                pageNumber: 24,
                title: 'X is for Xmas',
                description: 'Learn the letter X with a festive Xmas model',
                imageUrl: '/assets/scanimage/pattern-xmas.png',
                arModelUrl: '/models/xmas.glb',
                audioUrl: '/audio/xmas-pronunciation.mp3',
                interactiveElements: [
                    { id: 'xmas-hotspot', type: 'hotspot', name: 'Tap to Jingle', action: 'play_animation' },
                ],
            },
            {
                id: 'page-025',
                pageNumber: 25,
                title: 'Y is for Yatch',
                description: 'Learn the letter Y with a yatch/boat model',
                imageUrl: '/assets/scanimage/pattern-yatch.png',
                arModelUrl: '/models/yatch.glb',
                audioUrl: '/audio/yatch-pronunciation.mp3',
                interactiveElements: [
                    { id: 'yatch-hotspot', type: 'hotspot', name: 'Tap to Sail', action: 'play_animation' },
                ],
            },
            {
                id: 'page-026',
                pageNumber: 26,
                title: 'Z is for Zebra',
                description: 'Learn the letter Z with a striped zebra model',
                imageUrl: '/assets/scanimage/pattern-zebra.png',
                arModelUrl: '/models/zebra.glb',
                audioUrl: '/audio/zebra-pronunciation.mp3',
                interactiveElements: [
                    { id: 'zebra-hotspot', type: 'hotspot', name: 'Tap to Gallop', action: 'play_animation' },
                ],
            },
        ],
    },
    {
        id: 'book-002',
        title: '123 Count & Learn',
        description: 'Learn numbers 1-10 with engaging 3D models and counting activities.',
        coverImage: '/assets/ar-books/numbers-cover.jpg',
        category: 'numbers',
        ageGroup: '2-4 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-01-20',
        isFeatured: true,
        views: 980,
        rating: 4.7,
        pages: [
            {
                id: 'page-101',
                pageNumber: 1,
                title: 'Number 1 - One Apple',
                description: 'Learn number 1 with one apple',
                imageUrl: '/assets/ar-books/numbers/page-1.jpg',
                arModelUrl: '/models/apple.glb',
                audioUrl: '/audio/number-1.mp3',
            },
        ],
    },
    {
        id: 'book-003',
        title: 'Wild Animals Expedition',
        description: 'Explore wild animals in their natural habitats with amazing 3D AR models.',
        coverImage: '/assets/ar-books/animals-cover.jpg',
        category: 'animals',
        ageGroup: '3-5 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-02-01',
        isFeatured: true,
        views: 1500,
        rating: 4.9,
        pages: [
            {
                id: 'page-201',
                pageNumber: 1,
                title: 'The Mighty Lion',
                description: 'Meet the king of the jungle',
                imageUrl: '/assets/ar-books/animals/lion-page.jpg',
                arModelUrl: '/models/lion.glb',
                audioUrl: '/audio/lion-roar.mp3',
                interactiveElements: [
                    {
                        id: 'lion-sound',
                        type: 'button',
                        name: 'Listen to Roar',
                        action: 'play_sound',
                    },
                ],
            },
        ],
    },
    {
        id: 'book-004',
        title: 'Rainbow Shapes',
        description: 'Learn geometric shapes in vibrant colors with interactive 3D models.',
        coverImage: '/assets/ar-books/shapes-cover.jpg',
        category: 'shapes',
        ageGroup: '2-4 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-02-10',
        isFeatured: false,
        views: 750,
        rating: 4.6,
        pages: [],
    },
    {
        id: 'book-005',
        title: 'Magical Tales',
        description: 'Enchanting stories brought to life with augmented reality animations.',
        coverImage: '/assets/ar-books/stories-cover.jpg',
        category: 'stories',
        ageGroup: '3-5 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-02-15',
        isFeatured: false,
        views: 1100,
        rating: 4.8,
        pages: [],
    },
    {
        id: 'book-006',
        title: 'Science Explorer',
        description: 'Discover the wonders of science with interactive 3D experiments.',
        coverImage: '/assets/ar-books/science-cover.jpg',
        category: 'science',
        ageGroup: '4-6 years',
        authorName: 'Ank Square Team',
        publishedDate: '2024-02-20',
        isFeatured: true,
        views: 890,
        rating: 4.7,
        pages: [],
    },
];

export const defaultARBook: ARBook = {
    id: 'book-default',
    title: 'Welcome to AR Books',
    description: 'Start your journey with augmented reality learning',
    coverImage: '/assets/ar-books/default-cover.jpg',
    category: 'alphabet',
    ageGroup: '2-6 years',
    authorName: 'Ank Square Team',
    publishedDate: '2024-01-01',
    isFeatured: false,
    views: 0,
    rating: 5,
    pages: [],
};
