export const contactDashboardTranslations = {
  en: {
    title: 'Contact Dashboard',
    totalContacts: 'Total Contacts',
    new: 'New',
    replied: 'Replied',
    resolved: 'Resolved',
    archived: 'Archived',
    search: 'Search by name, email or phone...',
    downloadData: 'Download Data',
    allStatus: 'All Status',
    date: 'Date',
    name: 'Name',
    email: 'Email',
    contact: 'Contact',
    message: 'Message',
    notes: 'Notes',
    status: 'Status',
    action: 'Action',
    loading: 'Loading contacts...',
    noResults: 'No contacts found',
    call: 'Call',
    whatsapp: 'WhatsApp',
    addNote: 'Add note',
    notesCount: (count: number) => `${count} note${count !== 1 ? 's' : ''}`,
    notesFor: 'Notes for',
    noteHistory: 'Note History',
    noteNumber: (num: number) => `Note #${num}`,
    writeNewNote: 'Write New Note',
    addNewNote: 'Add New Note',
    newNote: 'New Note',
    close: 'Close',
    saveNote: 'Save New Note',
    saving: 'Saving...',
    deleting: 'Deleting...',
    delete: 'Delete',
    deleteSuccess: 'Note deleted successfully',
    deleteError: 'Failed to delete note',
    saveSuccess: 'Note added successfully',
    saveError: 'Failed to save note',
    statusUpdated: 'Status updated successfully',
    updateError: 'Failed to update status',
    fetchError: 'Failed to fetch contacts',
    enterNote: 'Please enter a note',
    selectContact: 'Please select a contact first',
    placeholderNote: 'Write your note here... e.g., "Follow up next week"',
    showingResults: (start: number, end: number, total: number) => 
      `Showing ${start} to ${end} of ${total} contacts`,
    itemsPerPage: 'Items per page:',
    pageOf: (current: number, total: number) => `Page ${current} of ${total}`,
    previous: 'Previous',
    next: 'Next',
    notesIndicator: 'notes'
  },
  hi: {
    title: 'संपर्क डैशबोर्ड',
    totalContacts: 'कुल संपर्क',
    new: 'नया',
    replied: 'जवाब दिया गया',
    resolved: 'समाधान किया गया',
    archived: 'अभिलेखीकृत',
    search: 'नाम, ईमेल या फोन से खोजें...',
    downloadData: 'डेटा डाउनलोड करें',
    allStatus: 'सभी स्थिति',
    date: 'तारीख',
    name: 'नाम',
    email: 'ईमेल',
    contact: 'संपर्क',
    message: 'संदेश',
    notes: 'नोट्स',
    status: 'स्थिति',
    action: 'कार्रवाई',
    loading: 'संपर्क लोड हो रहे हैं...',
    noResults: 'कोई संपर्क नहीं मिला',
    call: 'कॉल करें',
    whatsapp: 'व्हाट्सएप',
    addNote: 'नोट जोड़ें',
    notesCount: (count: number) => `${count} नोट${count !== 1 ? 'स' : ''}`,
    notesFor: 'के लिए नोट्स',
    noteHistory: 'नोट इतिहास',
    noteNumber: (num: number) => `नोट #${num}`,
    writeNewNote: '✍️ नया नोट लिखें',
    addNewNote: '➕ नया नोट जोड़ें',
    newNote: 'नया नोट',
    close: 'बंद करें',
    saveNote: 'नया नोट सहेजें',
    saving: 'सहेज रहे हैं...',
    deleting: 'हटा रहे हैं...',
    delete: 'हटाएं',
    deleteSuccess: 'नोट सफलतापूर्वक हटा दिया गया',
    deleteError: 'नोट हटाने में विफल',
    saveSuccess: 'नोट सफलतापूर्वक जोड़ा गया',
    saveError: 'नोट सहेजने में विफल',
    statusUpdated: 'स्थिति सफलतापूर्वक अपडेट की गई',
    updateError: 'स्थिति अपडेट करने में विफल',
    fetchError: 'संपर्क लाने में विफल',
    enterNote: 'कृपया एक नोट दर्ज करें',
    selectContact: 'कृपया पहले एक संपर्क चुनें',
    placeholderNote: 'यहां अपना नोट लिखें... जैसे, "अगले सप्ताह फॉलो अप करें"',
    showingResults: (start: number, end: number, total: number) => 
      `${start} से ${end} तक ${total} संपर्क दिखा रहे हैं`,
    itemsPerPage: 'प्रति पृष्ठ वस्तुएं:',
    pageOf: (current: number, total: number) => `पृष्ठ ${current} का ${total}`,
    previous: 'पिछला',
    next: 'अगला',
    notesIndicator: 'नोट्स'
  }
};

export type LanguageType = 'en' | 'hi';
